CONNECT / AS SYSDBA

spool sys.log

SET SERVEROUTPUT ON
SET DEFINE OFF
SET SCAN OFF
SELECT USER
  ||' @ '
  ||GLOBAL_NAME
  || '    '
  || TO_CHAR(SYSDATE,'dd-MON-yy hh24:MI:ss') AS ENVIRONMENT
FROM GLOBAL_NAME;

SET SERVEROUTPUT ON;
SET LINESIZE 2000;
SET PAGESIZE 200;
SET FEEDBACK OFF;
SELECT UPPER(RPAD(INSTANCE_NAME,40)) AS "DATABASE INSTANCE : " FROM V$INSTANCE;
SELECT SYSTIMESTAMP AS "TIME OF EXECUTION : " FROM DUAL;
prompt REFRESHING GRANTS AND SYNONYMS

prompt GRANTS AND SYNONYMS REFRESHED
prompt COMPILING USER : CM_AUDITLOG
EXEC DBMS_UTILITY.COMPILE_SCHEMA('AUDITLOG_TRIAL' );
prompt COMPILING USER : CRF
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CRF_TRIAL' );
prompt COMPILING USER : CRDM
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CRDM_TRIAL' );
prompt COMPILING USER : CIF
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CIF_TRIAL' );
prompt COMPILING USER : CM_NOTES
EXEC DBMS_UTILITY.COMPILE_SCHEMA('NOTES_TRIAL' );
prompt COMPILING USER : CPF
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CPF_TRIAL' );
prompt COMPILING USER : CS_AUDITLOG_REPORT
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CS_AUDITLOG_REPORT_TRIAL' );
prompt COMPILING USER : CENTURY_SHIELD
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CENTURY_SHIELD_TRIAL' );
prompt COMPILING USER : CM_STAGING
EXEC DBMS_UTILITY.COMPILE_SCHEMA('STAGING_TRIAL' );
prompt COMPILING USER : CMSTAGING_PRI
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CMSTAGING_PRI_TRIAL' );
prompt COMPILING USER : ARCHIVE
EXEC DBMS_UTILITY.COMPILE_SCHEMA('ARCHIVE_TRIAL' );
prompt COMPILING USER : CM_STUB
EXEC DBMS_UTILITY.COMPILE_SCHEMA('STUB_TRIAL' );
prompt COMPILING USER : CSO
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CSO_TRIAL' );
prompt COMPILING USER : CM
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CM_TRIAL' );
prompt COMPILING USER : CRPT
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CRPT_TRIAL' );
prompt COMPILING USER : CIMS
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CIMS_TRIAL' );
prompt COMPILING USER : PL
EXEC DBMS_UTILITY.COMPILE_SCHEMA('PL_TRIAL' );
prompt COMPILING USER : CDM
EXEC DBMS_UTILITY.COMPILE_SCHEMA('CDM_TRIAL' );

SELECT RPAD(OWNER,20) AS OWNER, RPAD(OBJECT_NAME,35) AS OBJECT_NAME, OBJECT_TYPE FROM DBA_OBJECTS WHERE STATUS = 'INVALID' AND OWNER LIKE ('%') ORDER BY 1,3,2;
prompt SCRIPT EXECUTION FINISHED : CHECK FILE RESULT.log FOR DETAILS
SET FEEDBACK ON;

SELECT SYSTIMESTAMP AS "TIME OF EXECUTION : " FROM DUAL;

spool off
